-- liquibase formatted sql

-- changeset yarakhovich_i:1
create table sensor
(
    sensor_id      bigint generated by default as identity,
    name           varchar(255) not null,
    model          varchar(255) not null,
    range_from     integer,
    range_to       integer      not null,
    sensor_type_id bigint       not null,
    sensor_unit_id bigint,
    description    varchar(255),
    location       varchar(255),
    primary key (sensor_id)
);

create table sensor_type
(
    sensor_type_id bigint not null,
    name           varchar(255),
    primary key (sensor_type_id)
);

create table sensor_unit
(
    sensor_unit_id bigint not null,
    name           varchar(255),
    primary key (sensor_unit_id)
);

alter table if exists sensor add constraint fk_sensor_type_id foreign key (sensor_type_id) references sensor_type;
alter table if exists sensor add constraint fk_sensor_unit_id foreign key (sensor_unit_id) references sensor_unit;